version: '3.8'

services:
  server:
    build: ./services/server
    command: python tema.py run -h 0.0.0.0
    volumes:
      - ./services/server/:/tmp/app
    ports: 
      - 5432:5432
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=meteo_user
      - POSTGRES_PASSWORD=meteo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5001:5001
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

volumes:
  postgres_data: