version: '3.8'

services:
  server:
    build: ./services/server
    command: python tema.py run -h 0.0.0.0
    volumes:
      - ./services/server/:/tmp/app
    ports: 
      - 5000:5000
  db:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5001:5001

volumes:
  postgres_data: