version: '3.8'

services:
  server:
    depends_on:
      - db
    build: ./server
    hostname: server
    container_name: server
    volumes:
      - ./server/:/tmp/app
    command: ["./wait-for-it.sh", "db:${POSTGRES_PORT}","--", "python" , "tema.py" , "run", "-h", "0.0.0.0"]
    networks:
      - server-network
    ports: 
      - ${SERVER_PORT}:5000
  db:
    restart: always
    image: postgres:latest
    hostname: db
    container_name: db
    env_file:
      - './credentials.env'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - admin-network
      - server-network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    restart: always
    env_file:
      - './credentials.env'
    ports:
      - ${AGENT_PORT}:80
    networks:
      - admin-network

volumes:
  postgres_data:

networks:
  server-network:
    driver: bridge
  admin-network:
    driver: bridge